mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from store.views import login_view, register_view, logout_view

urlpatterns = [
    
    path('admin/', admin.site.urls),
    
    path('system/', include('firestationsystem.urls')),
    path('store/', include('store.urls')),
    
    path('', home),
    path('login/', login_view, name='login'),
    path('signup/', register_view, name='signup'),
    path('logout/', logout_view, name='logout')
    
]

store/urls.py
from django.urls import path, include
from . import views
from .views import (ItemListView, ItemDetailView, ItemCreateView, ItemUpdateView,
                    CreateOrderView, OrderUpdateView, ajax_search_products, ajax_add_product, ajax_modify_order_item)
from .filters import Item_Filter

app_name = 'store'
urlpatterns = [
    path('items/', views.ItemListView.as_view(), name='item-index'),
    path('create/', views.ItemCreateView.as_view(), name='item-create'),
    path('detail/<int:id>/', views.ItemDetailView.as_view(), name='item-detail'),
    path('update/<int:id>/', views.ItemUpdateView.as_view(), name='item-create'),
    path('pos/', CreateOrderView.as_view(), name='create-order'),
    path('transaction/<int:pk>/', OrderUpdateView.as_view(), name='update_order'),

    #ajax add item in order
    path('ajax/search-products/<int:pk>/', ajax_search_products, name='ajax-search'),
    path('ajax/add-product/<int:pk>/<int:dk>/', ajax_add_product, name='ajax-add'),
    path('ajax/modify-product/<int:pk>/<slug:action>', ajax_modify_order_item, name='ajax_modify'),
]

store/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Sum
from djmoney.models.fields import MoneyField
from django.contrib.auth.models import User
from django.db.models.signals import post_delete
from django.dispatch import receiver

import datetime
from decimal import Decimal

class OrderManager(models.Manager):

    def active(self):
        return self.filter(active=True)


class Item(models.Model):
    creation = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, editable=False, null=True, blank=True, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=100, unique=True)
    item_status = models.BooleanField(default=True)
    item_price = models.DecimalField(decimal_places=2, max_digits=10, default=0.00)
    item_cost = models.DecimalField(decimal_places=2, max_digits=10, default=0.00)
    item_margin = models.DecimalField(decimal_places=2, max_digits=10, default=0.00)
    item_description = models.TextField()


    def __str__(self):
        return '%s' % (self.item_name)


    def get_absolute_url(self):
        return reverse("store:item-index")


class Order(models.Model):
    date = models.DateTimeField(default=datetime.datetime.now())
    creation = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    title = models.CharField(blank=True, max_length=150)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    is_paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-date']

    def save(self, *args, **kwargs):
        order_items = self.order_items.all()
        self.total_price = order_items.aggregate(Sum('total_price'))['total_price__sum'] if order_items.exists() else 0.00
        print(self.total_price)
        super().save(*args, **kwargs)


    def __str__(self):
        return 'Order {0}'.format(self.id)

class OrderItem(models.Model):
    
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_items')
    quantity = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, verbose_name="Item Total")

    def save(self, *args, **kwargs):
        self.total_price = Decimal(self.quantity) * Decimal(self.price)
        super().save(*args, **kwargs)
        self.order.save()

@receiver(post_delete, sender=OrderItem)
def delete_order_item(sender, instance, **kwargs):
    item = instance.item
    item.save()
    instance.order.save()




# Create your models here.

store/forms.py
from django import forms
from .models import Item, Order, OrderItem
from django.contrib.auth import (
        authenticate,
        get_user_model
)

User = get_user_model()

class BaseForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class OrderCreateForm(BaseForm, forms.ModelForm):
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = ['date', 'title' ]

class OrderEditForm(BaseForm, forms.ModelForm):

    class Meta:
        model = Order
        fields = ['date', 'title', 'is_paid']

class UserLoginForm(forms.Form):
        username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
        password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

        def clean(self, *args, **kwargs):
                username = self.cleaned_data.get('username')
                password = self.cleaned_data.get('password')
                
                if username and password:
                        user = authenticate(username=username, password=password)
                        if not user:
                                raise forms.ValidationError('This user does not exist')
                        if not user.check_password(password):
                                raise forms.ValidationError('Incorrect password')
                        if not user.is_active:
                                raise forms.ValidationError('This user is not active')
                return super(UserLoginForm, self).clean(*args, **kwargs)

class UserRegisterForm(forms.ModelForm):
        username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
        email = forms.EmailField(label='Email Address', widget=forms.TextInput(attrs={'class': 'form-control'}))
        email2 = forms.EmailField(label='Confirm Email', widget=forms.TextInput(attrs={'class': 'form-control'}))
        password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
        
        class Meta:
                model = User
                fields = [
                        'username',
                        'email',
                        'email2',
                        'password'
                ]
        
        def clean(self, *args, **kwargs):
                email = self.cleaned_data.get('email')
                email2 = self.cleaned_data.get('email2')
                if email != email2:
                        raise forms.ValidationError('Emails must match')
                email_qs = User.objects.filter(email=email)
                if email_qs.exists():
                        raise forms.ValidationError('Email already exists')
                return super(UserRegisterForm, self).clean(*args, **kwargs)
                


class ItemModelForm(forms.ModelForm):
        item_name = forms.CharField(label='Item Name', required=True, widget=forms.TextInput(attrs={  
                                                                                                'class': 'form-control',
                                                                                                'placeholder': 'Item Name',
                                                                                                'onClick': 'this.select()'                                                             
        }))
        item_status = forms.CheckboxInput()
        item_price = forms.DecimalField(label='Item Price', min_value=0.00, initial=0.00, widget=forms.TextInput(attrs={
                                                                                                'class':'form-control',
                                                                                                'oninput':'get_item_margin()',
                                                                                                'onClick': 'this.select()'

        }))
        item_margin = forms.DecimalField(label='Item Margin', min_value=0.00, initial=0.00, widget=forms.TextInput(attrs={
                                                                                                'class':'form-control',
                                                                                                'oninput':'get_item_price()',
                                                                                                'onClick': 'this.select()'
        }))
        item_cost = forms.DecimalField(label='Item Cost', min_value=0.00, initial=0.00, widget=forms.TextInput(attrs={
                                                                                                'class':'form-control',
                                                                                                'onClick': 'this.select()'
        }))
        item_description = forms.CharField(label='Description', required=False, widget=forms.Textarea(attrs={
                                                                                                'placeholder': 'Item Description',
                                                                                                'rows': 10,
                                                                                                'cols': 100,
        }))
        class Meta:
                model = Item
                fields = [
                        'item_name',
                        'item_cost',
                        'item_margin',
                        'item_price',
                        'item_status',
                        'item_description',
                ]

store/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse, Http404, JsonResponse
from .models import Item, Order, OrderItem
from .forms import ItemModelForm, UserLoginForm, UserRegisterForm, OrderCreateForm, OrderEditForm
from django.contrib import messages
from django.urls import reverse_lazy
from django_tables2 import RequestConfig
from django.views.generic import (
    ListView,
    CreateView,
    DeleteView,
    UpdateView,
    DetailView
)
from .filters import Item_Filter
import json

from django.contrib.auth import (
        authenticate,
        get_user_model,
        login,
        logout,
)
from .tables import ItemTable, OrderItemTable
from django.template.loader import render_to_string


class CreateOrderView(CreateView):
    template_name = 'pos/form.html'
    form_class = OrderCreateForm
    model = Order

    def get_success_url(self):
        self.new_object.refresh_from_db()
        return reverse('update_order', kwargs={'pk': self.new_object.id})

    def form_valid(self, form):
        object = form.save()
        object.refresh_from_db()
        self.new_object = object
        return super().form_valid(form)

class OrderUpdateView(UpdateView):
    model = Order
    template_name = 'pos/order_update.html'
    form_class = OrderEditForm

    def get_success_url(self):
        return reverse('update_order', kwargs={'pk': self.object.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        instance = self.object
        qs_p = Item.objects.filter()[:12]
        items = ItemTable(qs_p)
        order_items = OrderItemTable(instance.order_items.all())
        RequestConfig(self.request).configure(items)
        RequestConfig(self.request).configure(order_items)
        context.update(locals())
        return context

def login_view(request):
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        if next:
            return redirect(next)
        return redirect('/')
    context = {
        'form' : form,
    }
    return render(request, 'login.html', context)

def register_view(request):
    next = request.GET.get('next')
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        if next:
            return redirect(next)
        return redirect('/')
    context = {
        'form' : form,
    }
    return render(request, 'signup.html', context)

def logout_view(request):
    logout(request)
    return redirect('/login')


class ItemCreateView(LoginRequiredMixin, CreateView):
    template_name = 'items/item_create.html'
    form_class = ItemModelForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class ItemListView(LoginRequiredMixin, ListView):
    model = Item
    template_name = 'items/item_index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = Item_Filter(self.request.GET, queryset=self.get_queryset())
        return context

class ItemDetailView(LoginRequiredMixin, DetailView):
    template_name = 'items/item_detail.html'
    queryset = Item.objects.all()

    def get_object(self):
        id = self.kwargs.get('id')
        return get_object_or_404(Item, id=id)

class ItemUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'items/item_create.html'
    form_class = ItemModelForm

    def get_object(self):
        id = self.kwargs.get('id')
        return get_object_or_404(Item, id=id)

#AJAX

def ajax_search_products(request, pk):
    instance = get_object_or_404(Order, id=pk)
    q = request.GET.get('q', None)
    items = Item.objects.filter(item_name__startswith=q) if q else Item.objects.all()
    items = items[:12]
    items = ItemTable(items)
    RequestConfig(request).configure(items)
    data = dict()
    data['items'] = render_to_string(template_name='include/product_container.html',
                                        request=request,
                                        context={
                                            'items': items,
                                            'instance': instance
                                        })
    return JsonResponse(data)

def ajax_add_product(request, pk, dk):
    instance = get_object_or_404(Order, id=pk)
    item = get_object_or_404(Item, id=dk)
    order_item, created = OrderItem.objects.get_or_create(order=instance, item=item)
    if created:
        order_item.quantity = 1
        order_item.price = item.item_price
    else:
        order_item.quantity += 1
    order_item.save()
    instance.refresh_from_db()
    order_items = OrderItemTable(instance.order_items.all())
    RequestConfig(request).configure(order_items)
    data = dict()
    data['result'] = render_to_string(template_name='include/order_container.html',
                                      request=request,
                                      context={'instance': instance,
                                               'order_items': order_items
                                               }
                                    )
    return JsonResponse(data)

def ajax_modify_order_item(request, pk, action):
    order_item = get_object_or_404(OrderItem, id=pk)
    item = order_item.item
    instance = order_item.order
    if action == 'remove':
        order_item.quantity -= 1
        if order_item.quantity < 1: order_item.quantity = 1
    if action == 'add':
        order_item.quantity += 1
    order_item.save()
    if action == 'delete':
        order_item.delete()
    data = dict()
    instance.refresh_from_db()
    order_items = OrderItemTable(instance.order_items.all())
    RequestConfig(request).configure(order_items)
    data['result'] = render_to_string(template_name='include/order_container.html',
                                      request=request,
                                      context={
                                          'instance': instance,
                                          'order_items': order_items
                                      }
                                      )
    return JsonResponse(data)





# def item_create(request):
#     form = item_creation()
#     if request.method == 'POST':
#         form = item_creation(request.POST)
#         if form.is_valid():
#             # item_price = form.cleaned_data['item_price']
#             # form.instance.item_margin = item_price
#             Item.objects.create(**form.cleaned_data)
#             # form.save()
#             form = item_creation()
#     context = {
#         'form': form
#     }
#     return render(request, 'items/item_create.html', context)




# def item_detail(request, item_id):
#     try:
#         items = Item.objects.get(pk=item_id)
#     except Item.DoesNotExist:
#         raise Http404("Item does not exist")
#     return render(request, 'items/item_detail.html', {'items': items})

store/templates/pos/form.html
{% load static %}


{% block content %}
    <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">{{ form_title }}</h4>
                        <div class="ml-auto text-right">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{% url 'store:item-create' %}">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">{{ form_title }}</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <form method="post" class="form-horizontal"> {% csrf_token %}
                                <div class="card-body">
                                    <h4 class="card-title">Personal Info</h4>
                                    {{ form }}
                                </div>
                                <div class="border-top">
                                    <div class="card-body">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- editor -->
                <!-- ============================================================== -->
                <!-- End PAge Content -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Right sidebar -->
                <!-- ============================================================== -->
                <!-- .right-sidebar -->
                <!-- ============================================================== -->
                <!-- End Right sidebar -->
                <!-- ============================================================== -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->

{% endblock %}

store/templates/pos/order_update.html
{% load static %}
{% comment %} {% extends 'landing/home.html' %}  {% endcomment %}
{% load render_table from django_tables2 %} 

{% block content %}

    <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    </head>

    <div class="page-wrapper">
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-12 d-flex no-block align-items-center">
                    <h4 class="page-title">{{ instance.date }} - {{ instance }}</h4>
                    <div class="ml-auto text-right">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">{{ instance }}</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="header">
                            <h5 class="card-title">Items</h5>
                             <input data-href='{% url "store:ajax-search" instance.id %}' type="text" class="form-control search_button" placeholder="Search">
                        </div>
                        <div class="card-body" id="product_container">

                            {% include 'include/product_container.html' %} 
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div id='order_item_container' class="card-body">
                            {% include 'include/order_container.html' %}
                        </div>
                    </div>

                    <div class="card">
                        <div class="header">Edit</div>
                        <div class="card-body">
                            <form method="post" class="form">{% csrf_token %}
                                {{ form }}
                                <br>
                                <button type="submit" class="btn btn-success">Save</button>
                            </form>
                        </div>
                    </div>
            </div>
        </div>
        </div>
    </div>

{% endblock %}

{% block extra_js %}
    {% include 'include/ajax_calls.html' %}
{% endblock %}

store/templates/pos/pos-transaction.html
{% load static %}
<html lang="en">
<head>
    {% include 'include/css.html' %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.5.1.js"
    integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
    crossorigin="anonymous"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link href="{% static 'css/pos.css' %}" rel="stylesheet" >
    <script src={% static 'js/pos.js' %} type='text/javascript'></script>
    <title>POS</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar sticky-top navbar navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">Home</a>



  
</body>
</html>